from quad_controller_rl.agents.base_agent import BaseAgent
from quad_controller_rl.agents.policy_search import RandomPolicySearch
from quad_controller_rl.agents.DDPG_takeoff import DDPG_takeoff
from quad_controller_rl.agents.DDPG_hover import DDPG_hover
